### ISSUE TITLE
Default to escaping HTML content before passing to optional renderer

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/markdown-it-amsmath#2]
I believe that we should first html-escape the content before passing to the renderer:

https://github.com/executablebooks/markdown-it-amsmath/blob/master/src/index.ts#L35

There could be an optional parameter to turn off this functionality, but if we are letting users override the renderer I think we should default to doing so safely.

**Comment by chrisjsewell** [comment]
> I believe that we should first html-escape the content before passing to the renderer

the content here is not HTML though; it is LaTeX, so I'm not sure if thats a good idea, e.g then `a < b` would become `a &lt; b`. Can katex/mathjax handle that?

**Comment by chrisjsewell** [comment]
for the default renderer we could escape just in case, or better just encapsulate it in `pre` tags, so it cannot be interpreted unsafely

**Comment by rowanc1** [comment]
Quite right - sorry this was me getting back up to speed and having these tests in markdown-it-myst unexpectedly failing on me. On that package it is currently setup **not** to parse the math, but let that be done downstream in the browser (and not package/include katex).

I do think you are right that this is the responsibility of the renderer (default is already escaping, which is good). I will open another issue around documenting that explicitly.

To your points: 

> for the default renderer we could escape just in case, or better just encapsulate it in `pre` tags, so it cannot be interpreted unsafely

Pre tags are decorational only: https://stackoverflow.com/a/17882288/817791 <scripts> still get executed in them, as well as `</pre>` 💥 

> the content here is not HTML though; it is LaTeX, so I'm not sure if thats a good idea, e.g then `a < b` would become `a &lt; b`. Can katex/mathjax handle that?

Off hand, at least katex can handle that, yes.
